#!/usr/bin/awk -f
# function
function rep_with() {
    gsub(/((mon|tues|wed(nes)?|thur(s)?|fri|sat(ur)?|sun)(day)?)\b)/,"$&")
    gsub(/^H[ou]\w+ing|[Hh][ou]\w+ing/,"Housekeeping")
    gsub(/^[BPF](ina)\w+|[bpf](ina)\w+/,"Finance")
    gsub(/^[SF]\w+l[es]\b/,"Sales")
    gsub(/F[A-Z][A-Z]\b/,"F&B")
    gsub(/P[A-Z][A-Z]\b/,"PMC")
    gsub(/^F[ro]!i\w+/,"Front Office")
    gsub(/[Ff](un)\w+[n]/,"function")
    gsub(/^[Aa]\w+[ae]t/,"Asset")
    gsub(/^[CK]\w+en\b|\b[CK]\w+en\b|ofisier/,"Kitchen")
    gsub(/^Ste\+\b/,"Steward")
    gsub(/Rupiah|(^Rp)|(Rp\b)/,"RM")
    gsub(/Timbermantau/,"Tim Pemantau")
    gsub(/Mas[sk]/,"Mas")
    gsub(/Rafiqah/,"RAFOC")
    gsub(/[az]eribadi/,"peribadi")
    gsub(/saikan/,"syarikat")
    gsub(/[Cc]aptain/,"Kapt.")
    gsub(/labat/,"lambat")
    gsub(/[Mm][ea][ps]\b/,"Mes")
    gsub(/\b[Hh]\w+[st]/,"Homestay")
    gsub(/Ali Jauh Tak Kuasa/,"AJK")
    gsub(/Bismarck Boira/,"Wisma Perwira")
    gsub(/[Ll][a-z]ndr[iy]/,"laundri")
    gsub(/[Rr]osak|kong\b|kaput/,"rosak")
    gsub(/^[Mm[ae]\w+(nt)\w+|\b[Mm[ae]\w+(nt)\w+/,"Maintenance")
    gsub(/[bB]\w+r[ou]+m/,"Dewan Perkasa")
    gsub(/st[a-z]\w+s/,"status")
    gsub(/sen\w+g/,"senang")
    gsub(/fil[a-z]\w+/,"filter")
    gsub(/[a-z]\w+dul/,"reshedule")
    gsub(/boom/,"bom")
    gsub(/mandu/,"maklumkan")
    gsub(/dorang/,"dia orang")
    gsub(/[Ss]abuk/,"sahur")
    gsub(/lepih/,"lebih")
    gsub(/\bM[o][kh][a-z]\w*/,"Mokhtar")
    gsub(/C[a-z]ba/,"Cuba")
    gsub(/bodeg/,"bodek")
    gsub(/[bp]{4,5}\w+an/,"berkenaan")
    gsub(/[h]\w+ap/,"berharap")
    gsub(/p\w+hati/,"puas hati")
    gsub(/Jum[a-z]\w+/,"Jumaat")
    gsub(/riba\b/,"remain")
    gsub(/([A-Z]{1})JK/,"AJK")
    gsub(/F[A-Z]B\b/,"F\\&B")
    gsub(/[a-z]\w+uet/,"Banquet")
    gsub(/p+urus\w+an\b|[Pp]erjudian/,"pengurusan")
    gsub(/purus|pertengkor/,"pengurus")
    gsub(/N[ai][nm]t[ae[kq]/,"tag nama")
    gsub(/Ryan Fah/,"Rank \\& File")
    gsub(/[Mm][oa]nd[ai][ry]/,"Monday")
    gsub(/chat/,"cat")
    gsub(/[a-z]ive\sin/,"living in")
    gsub(/p[aei]yment/,"payment")
    gsub(/roskan/,"uruskan")
    gsub(/\[Rr]\w+dan\b/,"Ramadan")
    gsub(/refresh/,"request")
    gsub(/tak pergi/,"tak beri")
    gsub(/polisir/,"confused")
    gsub(/berhampir/,"En. Ibrahim")
    gsub(/food friend/,"full strength")
    gsub(/D[A-Z]P\b/,"DMP")
    gsub(/ramdin/,"go around")
    gsub(/b[uo]b[uo]\b/,"bubur")
    gsub(/lambok/,"lambuk")
    gsub(/Expiration/,"as per chef")
    gsub(/NX|nx/,"Annex")
    gsub(/hurricane/,"High-Gate")
    gsub(/100 grade/,"under grade")
    gsub(/[dD]e\w[uo]/,"deko")
    gsub(/tak lawan/,"tak tahu")
    gsub(/[a-z]+ding/,"tangguh")
    gsub(/Syibetang/,"shift ptg")
    gsub(/Syirani/,"shift pagi")
    gsub(/Syamala/,"shift malam")
    gsub(/shalam/,"Shah Alam")
    gsub(/Syiwat/,"Steward")
    gsub(/Syif/,"Cif")
    gsub(/Serami/,"Serambi")
    gsub(/wrap time/,"raptai")
    gsub(/attender/,"attenden")
    gsub(/[Oo][bdp]\w+[i]\b/,"Obai")
    gsub(/formulator/,"formal letter")
    gsub(/beri sahur/,"beritahu")
    gsub(/maduai/,"event")
    gsub(/marki/,"maki")
    gsub(/leni/,"Lanai")
    gsub(/skimpy/,"sekuriti")
    gsub(/perhati/,"puas hati")
    gsub(/nak meluat/,"naik meluat")
    gsub(/tanggipul/,"talipon")
    gsub(/berjabat/,"pejabat")
    gsub(/set rumput/,"0.4")
    gsub(/setapi|starting/,"staffing")
    gsub(/[Pp]erma\w+tor/,"Confirmation Letter")
    gsub(/Alliance/,"liase")
    gsub(/bulat/,"berbulan")
    gsub(/saya buka soap lagi/,"assalamualaikum, selamat pagi")
    gsub(/Stuffing/,"Staffing")
    gsub(/mist\w+[g]/,"fogging")
    gsub(/kena [Rr]azak|General Zang/,"Kol Razak")
    gsub(/(kod)\w+i/,"koordinasi")
    gsub(/[pm]\w+house/,"penthouse")
    gsub(/jadian/,"hari jadi")
    gsub(/betang/,"petang")
    gsub(/toste/,"toast")
    gsub(/siwik/,"pembekal")
    gsub(/s[aie]tt\W+e/,"settle")
    gsub(/\b[A-Z][A-Z]D/,"PTD")
    gsub(/clini[cg]/,"clinic")
    gsub(/[Tt]\w+[po][ed]\b/,"thypoid")
    gsub(/periwangan/,"pembelian")
    gsub(/Raghani/,"Razali")
    gsub(/penampahan/,"penambahan")
    gsub(/buka water/,"buat order")
    gsub(/leek/,"leak")
    gsub(/[0-9],/,/[0-9]/" ,")
    gsub(/diskap/,"discuss")
    gsub(/selfie/,"")
    gsub(/penampakan/,"penambahan")
    gsub(/ada gas/,"ada guest")
    gsub(/part point/,"4.")
    gsub(/\w+ian\b|pendana/,"pengendalian")
    gsub(/peman\w+/,"Pemantau")
    gsub(/Ibarat/,"Imbara")
    gsub(/part 4|boyang/,"foyer")
    gsub(/4 year/,"foyer")
    gsub(/4[Uu]|[Ff][our]\b/,"foyer")
    gsub(/[Bb]oru/,"Ballroom")
    gsub(/[Pp]eso[s]/,"pek")
    gsub(/pentas ginger/,"F&B Manager")
    gsub(/[Kk]onten|position/,"quotation")
    gsub(/penyempatan/,"pengesahan")
    gsub(/penyempatan/,"extend")
    gsub(/beter/,"better")
    gsub(/local/,"loker")
    gsub(/ibu/,"minggu")
    gsub(/pecesin/,"purchasing")
    gsub(/[Dd]\w+[iy]\b/,"daily")
    gsub(/Bill IA/,"bil air")
    gsub(/Louis Inn|UV/,"living-in")
    gsub(/Transi\w/,"Transit")
    gsub(/[Rr][ou]m\b)/,"room")
    gsub(/Railover/,"available")
    gsub(/standar\b/,"standard")
    gsub(/lo[ck][ae][rl]/,"loker")
    gsub(/kejar/,"kerja")
    gsub(/best-lip/,"payslip")
    gsub(/[A-Z]OD\b/,"HOD")
    gsub(/Mayday/,"Monday")
    gsub(/boyar/,"foyer")
    gsub(/\w+cap/,"touch up")
    gsub(/mor[ae]y/,"moreh")
    gsub(/home\w+/,"homestay")
    gsub(/ofiser/,"officer")
    gsub(/pendidik/,"candidate")
    gsub(/lokemart/,"Lokman")
    gsub(/polak/,"fol up")
    gsub(/dilat|de\w+xe/,"Deluxe")
    gsub(/wasiat/,"WhatsApp")
    gsub(/aban/,"Oven")
    gsub(/fair/,"kipas")
    gsub(/[Oo]rgani[sz]ation cat|[Oo]cat/,"org. chart")
}
